version: "3.9"
services:
  nats:
    image: nats-streaming
    ports:
      - "8222:8222"
    networks: ["nats"]
  nats-1:
    image: nats-streaming
    command: "--cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"
    networks: ["nats"]
    depends_on: ["nats"]
  nats-2:
    image: nats-streaming
    command: "--cluster nats://0.0.0.0:6222 --routes=nats://ruser:T0pS3cr3t@nats:6222"
    networks: ["nats"]
    depends_on: ["nats"]
  nats-webui:
    image: sphqxe/nats-webui:latest
    ports:
      - "9222:80"
    networks: [ "nats" ]
    depends_on: [ "nats" ]

networks:
  nats:
    name: nats